# Generated by Django 3.2.4 on 2024-03-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0004_hktdc'),
    ]

    operations = [
        migrations.AddField(
            model_name='webscraping',
            name='source_csv_file',
            field=models.FileField(blank=True, null=True, upload_to='source-csv-files'),
        ),
    ]
