# Generated by Django 3.2.4 on 2024-03-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0005_webscraping_source_csv_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='webscraping',
            name='category_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webscraping',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
