# Generated by Django 3.2.4 on 2024-03-27 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0006_auto_20240328_0231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webscraping',
            name='category_text',
        ),
        migrations.AddField(
            model_name='webscraping',
            name='item',
            field=models.CharField(blank=True, choices=[], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='webscraping',
            name='subcategory',
            field=models.CharField(blank=True, choices=[], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='webscraping',
            name='category',
            field=models.CharField(blank=True, choices=[('Automobile & Transport', 'Automobile & Transport'), ('Electronics', 'Electronics'), ('Fashion, Clothing & Accessories', 'Fashion, Clothing & Accessories'), ('Food & Beverage', 'Food & Beverage'), ('Gifts, Toys & Sports Supplies', 'Gifts, Toys & Sports Supplies'), ('Health, Beauty and Baby Care', 'Health, Beauty and Baby Care'), ('Home Products, Lights & Constructions', 'Home Products, Lights & Constructions'), ('Industrial Machinery, Parts & Raw Materials', 'Industrial Machinery, Parts & Raw Materials'), ('Jewellery & Watch', 'Jewellery & Watch'), ('Printing & Packaging, Stationery & Office Equipment', 'Printing & Packaging, Stationery & Office Equipment'), ('Professional Services', 'Professional Services')], max_length=255, null=True),
        ),
    ]
