# Generated by Django 3.2.4 on 2024-03-27 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0008_auto_20240328_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webscraping',
            name='item',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='webscraping',
            name='subcategory',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
